### ISSUE TITLE
Can't update chart title with custom hook?

### ISSUE THREAD

**Issue by zack6849** [Chartisan/Chartisan#10]
Hi There!

I'm using chartjs and chartisan, and I'm not able to update the title of the chart

My approach was to set the desired title in the custom attributes that come back, and try to pass that to chartjs

```
this.chart = new Chartisan({
      el: this.$refs.chartContainer,
      url: this.url,
      hooks: new ChartisanHooks()
          .responsive()
          .beginAtZero()
          .colors()
          .legend(false)
          .title({text: ' Placeholder title goes here.'})
          .custom(({data, merge, server}) => {
            console.log(server.chart);
            this.refreshTable(server.chart);
            return data;
          })
    });

    refreshTable(server_data){
      console.log(this.chart); //chartisan instance
      console.log(this.chart.chart); //chartjs instance (undefined when this runs), but if i store the output of the above line as a variable i can do temp0.chart in console, and access the chartjs instance, so my assumption is the instance is created shortly after this runs.
    }

```

When the update runs, this.chart.chart (the chartjs instance of the chartisan instance) doesn't exist
I can't seem to figure out a way around this, is this a use -case the library supports, or am I doing something silly?

Thanks,

**Comment by ConsoleTVs** [comment]
Haha, hooks run before the instance is created!!

The fun part is that every time we update or create the chart, we first run hooks, then create imstance and pass the hooks result to it. That means that instead of modifying the instance, you need to modify the data of the hooks. Try to log the current "data" variable on the custom hook and you will see there is the placeholder title somewhere in the object. You can modify that prop and return the whole object like u doing!

**Comment by zack6849** [comment]
That seemed to do it, the below worked:
Thanks!

```
.custom(({data, merge, server}) => {
            data.options.title.text = server.chart.extra.title
            return data;
          })
```

**Comment by ConsoleTVs** [comment]
Yey! Fantastic! You also have a shorthabd using the .options() hook, read the docs ;)

**Comment by zack6849** [comment]
I knew about the options hook, though it wasn't clear from the documentation that options provides access to the server returned `extra` keys, is that the case?

**Comment by ConsoleTVs** [comment]
Oh whops, you're right, you must use custom one to use server data. My bad!
