### ISSUE TITLE
How to retrieve the original chart instance

### ISSUE THREAD

**Issue by pvanhemmen** [Chartisan/Chartisan#12]
I'm using the latest version of Chartisan with echarts and laravel. I retrieve all chart data from an url endpoint and in my case I don't know if there is any data to display. So normally what I would do is setup a listener to one of the [events](https://echarts.apache.org/en/api.html#events) on the chart and react accordingly, for exampe with an appropriate message.

Is there a way to retrieve the original chart instance after creation from the Chartisan object and register echarts event listeners? I noticed there is a chart.state() method implemented, but that's something I'd need to poll myself instead of just registering to an event.

Or maybe there is another way of intercepting data after it as been receieved in a hook which I don't know of?

Thanx in advance!

**Comment by ConsoleTVs** [comment]
You can do chart.chart. sounds bad but it will get the echarts instance

**Comment by ConsoleTVs** [comment]
https://github.com/Chartisan/Echarts/blob/a95b75fb8c31bbcad5e24f591d55c4f464edba68/src/index.ts#L25
