### ISSUE TITLE
How i can listen for events ?

### ISSUE THREAD

**Issue by DilawskyJordan** [Chartisan/Chartisan#18]
Hello, i am using chartisan with echarts and laravel . And i need to listen for events when clicking on a bar.
[https://echarts.apache.org/en/api.html#events.Mouse%20events.click](https://echarts.apache.org/en/api.html#events.Mouse%20events.click)
```
var chart = new Chartisan({
 el: '#chart',
 url: "@chart('....')",
    ....
});
chart.on("click", function() {
 console.log("Clicked");
})
```

**The error : Uncaught TypeError: chart.on is not a function**

**Comment by ConsoleTVs** [comment]
You can access the instance directly at the `.chart` attribute. Meaning...

```
var chart = new Chartisan({
 el: '#chart',
 url: "@chart('....')",
    ....
});
chart.chart.on("click", function() {
 console.log("Clicked");
})
```

**Comment by DilawskyJordan** [comment]
Hello , 
this method didn't work for me :
`var chart = new Chartisan({
 el: '#chart',
 url: "@chart('....')",
    ....
});
chart.chart.on("click", function() {
 console.log("Clicked");
})
`
chart.chart will return null.
So I figured a solution to wait the chart.cart to be available:
`var check = setInterval(function() {
		   if (chart.chart) {
		      chart.chart.on("click", function(params) {
		      	console.log("Hi now I can be executed")
		      })
		      	clearInterval(check)
		   }
		}, 100);`
