### ISSUE TITLE
Rendering multiple charts on the same page.

### ISSUE THREAD

**Issue by Sjos12** [Chartisan/Chartisan#26]
Hi, 

I was using your package for my personal project. I wanted to render multiple charts on one page but since the chart is initialized on a div with a unique id that wouldn't be possible without some workarounds. Since the number of charts that have to be rendered isn't constant, my first idea was to change the divs id for each chart that has to be rendered. Although this feels like a little bit of a workaround, so before I start I wanted to ask if there is a better way of approaching this. I'm using Laravel 8.0 for my project btw. 

Many thanks.

**Comment by ConsoleTVs** [comment]
If you are working with php the proposed solution does not seem that bad. An alternative to your solution is to use js for this. You can also pass a dom node to the element as opposed to a query selector, meaning you could create those nodes in a for loop, put them in the dom, and pass it to chartisan. At the end of the day you just need a div where chartisan can be initialized. A new version of chartisan is on the way with improvements to people using php and specially laravel. Let me know if you find issues about it!

**Comment by Sjos12** [comment]
Thanks for the reply. I'll just try the first solution and see if that works.
