### ISSUE TITLE
How do I change a line chart fill using custom hooks? 

### ISSUE THREAD

**Issue by Sjos12** [Chartisan/Chartisan#27]
I've been trying to understand the documentation regarding [hook customization](https://chartisan.dev/documentation/frontend/hooks#Custom-Hooks). However I can't seem to remove the fill from a line chart. I'm using ChartJS and Laravel, this is the .options() hook I have right now.  

```
.options({
                data: {
                    datasets: [{
                        fill:false,
                    }]
                },
            })
```

**Comment by ConsoleTVs** [comment]
Check out https://chartisan.dev/documentation/examples#Different-datasets

If you use a custom options hook, you'll need to append that fill to each existing dataset.

Things are about to change for the new upcoming version of Chartisan. And a new API will be on the way. For now, use the datasets hook to set the fill attribute to each dataset invividually:

```js
.datasets([{ type: 'line', fill: false }]),
```

**Comment by Sjos12** [comment]
Ah, you're right completely overlooked that. Thanks!
