### ISSUE TITLE
Documentation Req: How to utilize custom data?

### ISSUE THREAD

**Issue by zack6849** [Chartisan/Chartisan#5]
Hi There!

I'm trying to use your library along with your laravel charts package, and It's clear how to PASS custom data in the response, but aside from a vague reference to hooks, it's unclear to me how I'd go about accessing that data

EG:

```
 return Chartisan::build()
            ->labels(...)
            ->extra([
                'foo' => $foo,
                'bar' => $bar,
            ])
            ->dataset('Data', $data);
```

How would I access foo and bar on the front-end? 
Any assistance would be appreciated.

**Comment by zack6849** [comment]
Disregard, I missed the comment there about the server param.

**Comment by ConsoleTVs** [comment]
Yes, it's pretty easy:

```js
hooks.custom(({ data, merge, server }) => {
  // data ->   Contains the current chart configuration
  //           data that will be passed to the chart instance.
  // merge ->  Contains a function that can be called to merge
  //           two javascript objects and returns its merge.
  // server -> Contains the server information in case you need
  //           to acces the raw information provided by the server.
  //           This is mostly used to access the `extra` field.

  // ...

  // The function must always return the new chart configuration.
  return data
})
```

**Comment by ConsoleTVs** [comment]
Good to know :D , I stopped writting the answer because looks like you figured it out ;)


I'll try improving the docs at some point. Sorry if that wasn't clear.

**Comment by navidmetal** [comment]
do you help me more instead,appreciated?
i don't undrestand how to get extra data in frontend  with hooks.custom(({ data, merge, server }) or not  !??

**Comment by ConsoleTVs** [comment]
You need to use the `server` variable inside the custom hook to access the server information. Your server can use the `extra` method (included in all shipped adapters) to send those extra info that can be read using the `server` variable in the chartisan hooks.

**Comment by navidmetal** [comment]
Thank you for everything you have done in this project

**Comment by navidmetal** [comment]
ooh i forgot, after use hooks.custom the chart give an eror ( There was an error ), but data can be reachble, what can i do in this situation

**Comment by rudysetiawan** [comment]
so sorry being a noob here, how do I display those extra data into the html?

do i do something like this on the frontend?
```
 .custom(({server}) => {
                document.getElementById("invoice").innerHTML = server.invoice;
                document.getElementById("coupon").innerHTML = server.coupon;
            }),
```
backend is

```
  $chart = Chartisan::build()
            ->labels(['Payments'])
            ->extra(['invoice' => $total_invoice, 'coupon' => $total_coupon])
            ->dataset('Invoice',[$total_invoice])
            ->dataset('Coupon',[$total_coupon]);

```

**Comment by zack6849** [comment]
@rudysetiawan You'd want server.chart.extra.coupon I think.
Try checking the returned json in your browser network tab and also you could do a console.log of the server object to inspect it at runtime.
