### ISSUE TITLE
How can I pass options to the chartjs chart?

### ISSUE THREAD

**Issue by zack6849** [Chartisan/Chartisan#9]
Hi There!

Reading over your hooks, it looks like options hook should be what I want, but it doesn't seem to be working

```
 this.chart = new Chartisan({
      el: this.$refs.chartContainer,
      url: this.url,
      options: {
        cutoutPercentage: 75,
      },
      hooks: new ChartisanHooks()
          .responsive()
          .colors()
          .legend(false)
          .title('Healthy Widgets')
          .datasets('doughnut')
          .pieColors(["green", "red"])
          .options({
            cutoutPercentage: 75,
          })
    });
```

I tried setting the options in two places, just to see if either would work, neither does, and this is a documented option in chartjs: 

https://www.chartjs.org/docs/latest/charts/doughnut.html#config-options

In vanilla chartjs code, it'd look like this:

```
var chart = new Chart(ctx, {
    type: 'pie',
    data: {
        datasets: [{.....}],
        labels: [.....]
    },
    options: {
        title: {
            display: true,
            text: "Breakdown (Monthly)",
        },
        cutoutPercentage: 75,
    },
});
```

What am I doing wrong?

Thanks

**Comment by zack6849** [comment]
I figured this out a few minutes after finally giving in and submitting an issue, of course.

You need to nest options inside of options, since options from chartisan ends up in the root config for the chartjs object, eg, with the above code:

![screenshot](https://www.zcraig.me/files/MYQcnSl8x7yM59HXh5ceY7Og3.png)

Changing my code to this fixed my issue:

```
this.chart = new Chartisan({
      el: this.$refs.chartContainer,
      url: this.url,
      hooks: new ChartisanHooks()
          .responsive()
          .colors()
          .legend(false)
          .title('Healthy Widgets')
          .datasets('doughnut')
          .pieColors(["green", "red"])
          .options({
            options: {
              cutoutPercentage: 75,
            }
          })
    });
```

**Comment by ConsoleTVs** [comment]
Depends on what library you're using, they are just merged to the final object passed to the underlying lib ;)
